### ISSUE TITLE
Build failure on CentOS7 (GCC 7.3.0)

### ISSUE THREAD

**Issue by s-andrews** [Griffan/FASTQuick#10]
I tried to build the package on GCC 7.3.0 (default compiler on CentOS7) and got the build failure below.  It looks like the C++ 11 syntax needs to be explicitly enabled on this version of GCC, so could this be added to the makefile for a smoother proceedure for CentOS users?
[make.log](https://github.com/Griffan/FASTQuick/files/4853489/make.log)

**Comment by Griffan** [comment]
Hi,
The C++ 11 option is enabled by default in the CMAKE files.
It looks like your default compiler is using GCC 4.8.2 files, could you double-check the GCC version?

**Comment by s-andrews** [comment]
```
[andrewss@headstone ~]$ gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by s-andrews** [comment]
Ah - OK, I think I've found what might be happening.

This is an OpenOHPC system, which is based on CentOS7, but there are some differences, specifically they install a newer version of gcc, so whilst I get the repsonse above when I run gcc from the path, if I do:

```
[andrewss@headstone build]$ which gcc
/opt/ohpc/pub/compiler/gcc/7.3.0/bin/gcc
```

..but specifically running:

```
[andrewss@headstone build]$ /usr/bin/gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

..there is an older version around, but it's not the default.  It appears that the build system isn't using the PATH to identify which gcc to use.

So then, how do I tell the build system to use the /opt/ version of gcc?

**Comment by Griffan** [comment]
You can try
```
cmake -DCMAKE_CXX_COMPILER=/path/to/your/compiler ..
```
From the make.log, it appears to be related to the g++ version, so if this doesn't work, try this
```
cmake -DCMAKE_C_COMPILER=/path/to/your/compiler ..
```
from the build directory

**Comment by s-andrews** [comment]
Setting both of those variables allowed the build to complete.

Many thanks for your help with this.
