### ISSUE TITLE
Make test: all tests failed in conda environment

### ISSUE THREAD

**Issue by carlosmag** [Griffan/FASTQuick#8]
Hi.
Installing FASTQuick in conda env failed in `make test` step.
`cmake` did not complain about missing libraries.

Conda environment has the following packages installed:
`cmake 3.14.0 ; make 4.2.1 ; zlib 1.2.11 ; bzip2 1.0.8; backports.lzma 0.0.14 ; openssl 1.1.1g ; libcurl 7.69.1 ; htslib 1.10.2`
`SO: Ubuntu 18.04`

Maybe I am missing some prerequisite?
Thanks

**Comment by Griffan** [comment]
The problem is that there is one index file of ref.test.fa missing. It should be fine now. Please let me know if it still fails.

**Comment by Griffan** [comment]
It's also helpful that if you can post what the error message is in the file:
``` 
build/Testing/Temporary/LastTest.log
```

**Comment by carlosmag** [comment]
It works now! Thanks!
